services:
  - type: web
    name: docflow-backend
    env: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: RATE_LIMIT
        value: 100
