services:
  - type: web
    name: docflow-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: RATE_LIMIT
        value: 100
    disk:
      name: docflow-storage
      mountPath: /tmp
      sizeGB: 1